### ISSUE TITLE
Error Dumping Application

### ISSUE THREAD

**Issue by bmbernie** [as0ler/r2flutch#1]
When attempting to dump an application I ran into this error.  Any suggestions on how to proceed?

~~~
r2flutch XXXXX
[+] Open Application Process XXXXX
resumed spawned process.
[+] Mount Application Bundle
Mounted io on /r2f at 0x0
[+] Set block size to 0x80000

Invalid address (XXXXXw)
|ERROR| Invalid command 'mdj /r2f/AppBundle/assets/node_modules/@XXXX' (0x6d)
~~~

**Comment by as0ler** [comment]
Can you please give more detail information about the environment? 

- Device and iOS Version 

Is it happening always with the same App? I think I found the issue, however I just wanna reproduce it locally.

**Comment by bmbernie** [comment]
Hey Murphy,

It does happen every time attempt to dump this application.

I am on iOS 13.1.3.
The device is an iPhone X.

Thanks,
Brandon
