### ISSUE TITLE
ERROR - Failed to copy file: .gitkeep

### ISSUE THREAD

**Issue by itsmylife44** [as0ler/r2flutch#4]
iOS: 14.6
Device: iphone 7
Jailbrake tool: checkrain 

radare2: 5.5.4

MacBook-Pro-di-xspam:jan xspam$ r2flutch -i com.adobe.PSMobile
[+] Open Application Process com.adobe.PSMobile
resumed spawned process.
[+] Mount Application Bundle
Mounted io on /r2f at 0x0
[+] Set block size to 0x400000

[+] Loading all modules
[+] Dumping Module PS Express at 0x104b1d000 (0x1000 Bytes)
Dumped 4096 bytes from 0x104b1d000 into /var/folders/s1/t_833fyx34n_5r4xvjmd6kzr0000gn/T/r2flutch-diqkax00/dump/PS Express
File 'PS Express' created. (size: 101806432 bytes)
[+] Writing decrypted data to file /var/folders/s1/t_833fyx34n_5r4xvjmd6kzr0000gn/T/r2flutch-diqkax00/bin/PS Express at 0x21000
[+] Patching cryptid at offset 0x11b0
[+] Module /var/folders/s1/t_833fyx34n_5r4xvjmd6kzr0000gn/T/r2flutch-diqkax00/bin/PS Express successfully decrypted
[+] Copy application bundle to: /var/folders/s1/t_833fyx34n_5r4xvjmd6kzr0000gn/T/r2flutch-diqkax00/Payload/PS Express.app
[+] Copy App Bundle to disk
 15%|█████████████████████▋                                                                                                                          | 613/4069 [01:03<03:24, 16.90it/s][x] ERROR - Failed to copy file: .gitkeep
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4069/4069 [14:24<00:00,  4.71it/s]
[+] Creating IPA file at ./PS Express.ipa
[+] IPA file saved at ./PS Express.ipa
[*] SUCCESS - r2flutch Decryption Complete!

**Comment by as0ler** [comment]
For some reason r2frida is not copying the .gitkeeper file successfully. However, this file is not needed for the app (is part of the development process and it's an empty file).

In the last release (1.0.3) at least the error is not appearing anymore and the process finishes successfully.
